# Generated by Django 4.2 on 2024-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblContactos',
            fields=[
                ('id_contactos', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('apellidos', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('celular', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('cargo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=250, null=True)),
            ],
            options={
                'db_table': 'tbl_contactos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDistritos',
            fields=[
                ('id_distrito', models.AutoField(primary_key=True, serialize=False)),
                ('distrito', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('cod_postal', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'tbl_distritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEmpresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('razon_social', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('direccion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('telefono', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('web', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('tipo_empresa', models.IntegerField()),
                ('padre', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMaestra',
            fields=[
                ('id_tipo_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('id_padre', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('proveedor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_maestra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPersonas',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('apellidos', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('direccion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('celular', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('imagen', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=250, null=True)),
                ('estado', models.BooleanField()),
                ('tipo_usuario', models.IntegerField()),
                ('fec_creacion', models.DateTimeField()),
                ('fec_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_registro', models.IntegerField()),
                ('usuario_modificacion', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSeguimiento',
            fields=[
                ('id_seguimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_collation='Modern_Spanish_CI_AS')),
                ('fec_creacion', models.DateTimeField()),
                ('fec_asignacion', models.DateTimeField()),
                ('adjunto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTicket',
            fields=[
                ('id_ticket', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo_ticket', models.IntegerField()),
                ('titulo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('descripcion', models.TextField(db_collation='Modern_Spanish_CI_AS')),
                ('estado', models.IntegerField()),
                ('fec_creacion', models.DateTimeField()),
                ('fec_asignacion', models.DateTimeField()),
                ('adjunto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('id_persona_asignado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_ticket',
                'managed': False,
            },
        ),
    ]
